### PR TITLE
public_agents_extra_volumes support

### PR DESCRIPTION
**Pull request by jdef**
depends on https://github.com/dcos-terraform/terraform-aws-infrastructure/pull/27

cc @nfnt @fatz

### CODE REVIEW

**Comment by jdef** [comment]
not sure why CI is unhappy
```
[2019-06-05T16:13:58.803Z] Scanning dcos_core_variables.tf

[2019-06-05T16:13:58.803Z] 2019-06-05 16:13:58,696 - WARNING - Variable dcos_version with description "Specifies which DC/OS version instruction to use. Options: 1.12.3, 1.11.10, etc. See dcos_download_path or dcos_version tree for a full list." doesn't match description mapping "Specifies which DC/OS version instruction to use. Options: 1.13.1, 1.12.3, 1.11.10, etc. See dcos_download_path or dcos_version tree for a full list."

[2019-06-05T16:14:00.187Z] Terminated

script returned exit code 1
```

**Comment by fatz** [comment]
yep this got changed in 0.2.x and not backported into 0.1.x. In this case it would make sense but there could be other cases where we want different descriptions in the versions. CC: @sebbrandt87 

@jdef could you please for now set the variable `dcos_version`'s description to `Specifies which DC/OS version instruction to use. Options: 1.13.1, 1.12.3, 1.11.10, etc. See dcos_download_path or dcos_version tree for a full list.`

this will make the CI happy :)

**Comment by jdef** [comment]
more CI problems:
```
[2019-06-05T16:26:46.114Z]   Getting source "git::https://github.com/dcos-terraform/terraform-aws-dcos.git?ref=public_agents_extra_volumes"

[2019-06-05T16:26:46.114Z] Error downloading modules: Error loading modules: error downloading 'https://github.com/dcos-terraform/terraform-aws-dcos.git?ref=public_agents_extra_volumes': /usr/bin/git exited with 1: error: pathspec 'public_agents_extra_volumes' did not match any file(s) known to git.

[2019-06-05T16:26:46.114Z] 

script returned exit code 1
```

**Comment by fatz** [comment]
😆 thats a good one... the script thinks its a local branch :D cc: @sebbrandt87 

rest is looking good i'll merge

**Review by fatz — APPROVED** [review]
lgtm

**Pull request merged**
