### PR TITLE
Update links of DC/OS versions

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
They were outdated, the one I found seems to be the most up to date information

### CODE REVIEW

**Comment by fatz** [comment]
Hey @DanielMSchmidt sorry for the pretty late response. Thanks for your patch. Can you please update your branch and run 

```
docker run -ti -v$(pwd):/a --entrypoint /usr/bin/terraform-docs fatz/terraform-jenkins md /a > README.md
```

this will update the README.md so the new description will show up and the jenkins job wont fail anymore

**Comment by DanielMSchmidt** [comment]
Thank you for taking a look @fatz :)

**Comment by fatz** [comment]
well so d0dca6c looks good but the force push broke it so far...

**Comment by sebbrandt87** [comment]
This must be migrated to https://docs.google.com/spreadsheets/d/1sR9Iqds3RJ7tfxoo01YN2KoEqs1IGCOMH5yrxzDBs1g/edit#gid=0

**Comment by sebbrandt87** [comment]
it is part of our automation process, and we need to review links

**Pull request closed without merging**
